<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_TEST" Id="{3e1b042c-faae-06db-38f4-585c236d1642}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	FB_System_Test : FB_System_Test;
	FB_Clamp01_Test : FB_Clamp01_Test;
	FB_Compare_Test : FB_Compare_Test;
	FB_Norm_Test : FB_Norm_Test;
	FB_Scale_Test : FB_Scale_Test;
	FB_Sign_Test : FB_Sign_Test;
	FB_InverBytesOrder_Test : FB_InverBytesOrder_Test;
	FB_GetByte_Test : FB_GetByte_Test;
	FB_Swap_Test : FB_Swap_Test; 
	FB_MEMCPY_Test : FB_MEMCPY_Test;
	FB_Heater_Test : FB_Heater_Test;
	FB_MoveVelocity_Test : FB_MoveVelocity_Test;
	FB_MoveAbsolute_Test : FB_MoveAbsolute_Test; 
	FB_DriveControl_Test : FB_DriveControl_Test;
	FB_Button_Test : FB_Button_Test;
	FB_Switch_Test : FB_Switch_Test;
	FB_Lock_Test : FB_Lock_Test;
	FB_Panel_Test : FB_Panel_Test;
	FB_Cylinder_Test : FB_Cylinder_Test;
	FB_Device_Test : FB_Device_Test;
	FB_DeviceByte_Test : FB_DeviceByte_Test;
	FB_DeviceWord_Test : FB_DeviceWord_Test;
	FB_DeviceDWord_Test : FB_DeviceDWord_Test;
	FB_DeviceLWord_Test : FB_DeviceLWord_Test;
	FB_DeviceReal_Test : FB_DeviceReal_Test;
	FB_Drive_Test : FB_Drive_Test;
	FB_Lamp_Test : FB_Lamp_Test;
	FB_Reader_Test : FB_Reader_Test;
	FB_SensorAnalog_Test : FB_SensorAnalog_Test;
	FB_SensorBinary_Test : FB_SensorBinary_Test;
	FB_Robot_Test : FB_Robot_Test;	
	FB_AdsMessageHandler_Test : FB_AdsMessageHandler_Test;
	FB_RecordData_Test : FB_RecordData_Test;		
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>