<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Device" Id="{dea5f860-aad4-00ea-373e-8c1026875c07}" SpecialFunc="None">
    <Declaration><![CDATA[(*
	Basic device with default interface:
	nControl BYTE: From TwinCAT >>> To Unity
	nStatus BYTE: FROM Unity >>> TO TwinCAT		
*)
FUNCTION_BLOCK FB_Device EXTENDS FB_LinkDevice
VAR_INPUT		
	nControl  			: BYTE;
END_VAR

VAR_OUTPUT
	nStatus  			: BYTE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();
Control := nControl;
nStatus := Status;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>