<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Lamp" Id="{7fc594db-b88a-0a4e-01f1-22815165cbed}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Lamp EXTENDS FB_LinkDevice 
VAR_INPUT
	bEnable		: BOOL; //0-Lamp OFF, 1 - Lamp ON
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();
Control.0 := bEnable;]]></ST>
    </Implementation>
    <LineIds Name="FB_Lamp">
      <LineId Id="28" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>