<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_LogMessage" Id="{ed4f2247-b44f-058d-2ec0-af7645edcb84}" SpecialFunc="None">
    <Declaration><![CDATA[(*
	Log message to TwinCAT console
*)
{attribute 'hide_all_locals'}
FUNCTION F_LogMessage : BOOL
VAR_INPUT
	sMessage : T_MAXSTRING;
END_VAR

VAR CONSTANT	
	S_LOGHEADER		: T_MAXSTRING := 'Open Commissioning: %s';
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, S_LOGHEADER, sMessage);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>