<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_LinkDataLWord" Id="{1972ec6c-e9f1-0295-1c53-5bd7bae6e40c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LinkDataLWord EXTENDS FB_LinkDevice
VAR	
	{attribute 'simulation_interface'}
	ControlData		AT %Q* : LWORD;
	{attribute 'simulation_interface'}
	StatusData		AT %I* : LWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="GetLinkControlData" Id="{68aa099c-6f15-0510-3e8b-1c6ed923ba6b}">
      <Declaration><![CDATA[METHOD INTERNAL GetLinkControlData : LWORD

]]></Declaration>
      <Implementation>
        <ST><![CDATA[GetLinkControlData := ControlData;]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetLinkStatusData" Id="{e9556268-4f18-099e-3cf7-1fdb5bb0087e}">
      <Declaration><![CDATA[METHOD INTERNAL SetLinkStatusData : BOOL
VAR_INPUT
	nStatusData : LWORD;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[StatusData := nStatusData;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>