<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_GetLByte" Id="{cd10e641-289c-00b7-336d-c4f34a4bdec1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_GetLByte : BYTE
VAR_INPUT
	nWord	: WORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetLByte := WORD_TO_BYTE(nWord);]]></ST>
    </Implementation>
    <LineIds Name="F_GetLByte">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>