<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_Norm" Id="{decdff22-50cb-0d66-3778-8a2b19b7d782}" SpecialFunc="None">
    <Declaration><![CDATA[(*
	The input value will be normalized in the range of fMin to fMax.
	The returned value is within the range of 0 to 1.
*)
FUNCTION F_Norm : REAL
VAR_INPUT
	fMin 		: REAL; //Limit Min
	fMax 		: REAL; //Limit Max
	fValue 		: REAL; //Input Value
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Norm := F_Clamp01((fValue - fMin)/(fMax - fMin));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>